<?php

namespace PHPSQLParser\processors;

class ReturnProcessor extends ExpressionListProcessor
{
    public function process($tokens)
    {
        return parent::process($tokens); // TODO: Change the autogenerated stub
    }
}